package Environment;


/**
* Environment/EnvironmentalCentrePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:03 AM British Summer Time
*/

public abstract class EnvironmentalCentrePOA extends org.omg.PortableServer.Servant
 implements Environment.EnvironmentalCentreOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("raise_alarm", new java.lang.Integer (0));
    _methods.put ("register_agency", new java.lang.Integer (1));
    _methods.put ("register_regional_centre", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Environment/EnvironmentalCentre/raise_alarm
       {
         String center_name = in.read_string ();
         Environment.Reading readings_list[] = Environment.Set_of_readingsHelper.read (in);
         this.raise_alarm (center_name, readings_list);
         out = $rh.createReply();
         break;
       }

       case 1:  // Environment/EnvironmentalCentre/register_agency
       {
         String who = in.read_string ();
         String email = in.read_string ();
         String region_of_interest = in.read_string ();
         this.register_agency (who, email, region_of_interest);
         out = $rh.createReply();
         break;
       }

       case 2:  // Environment/EnvironmentalCentre/register_regional_centre
       {
         String centre_name = in.read_string ();
         this.register_regional_centre (centre_name);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Environment/EnvironmentalCentre:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public EnvironmentalCentre _this() 
  {
    return EnvironmentalCentreHelper.narrow(
    super._this_object());
  }

  public EnvironmentalCentre _this(org.omg.CORBA.ORB orb) 
  {
    return EnvironmentalCentreHelper.narrow(
    super._this_object(orb));
  }


} // class EnvironmentalCentrePOA
