package Environment;


/**
* Environment/EnvironmentalCentreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:03 AM British Summer Time
*/

public interface EnvironmentalCentreOperations 
{
  void raise_alarm (String center_name, Environment.Reading[] readings_list);
  void register_agency (String who, String email, String region_of_interest);
  void register_regional_centre (String centre_name);
} // interface EnvironmentalCentreOperations
