package Environment;


/**
* Environment/Log_of_alarm_readingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:02 AM British Summer Time
*/

public final class Log_of_alarm_readingsHolder implements org.omg.CORBA.portable.Streamable
{
  public Environment.Reading value[] = null;

  public Log_of_alarm_readingsHolder ()
  {
  }

  public Log_of_alarm_readingsHolder (Environment.Reading[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Environment.Log_of_alarm_readingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Environment.Log_of_alarm_readingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Environment.Log_of_alarm_readingsHelper.type ();
  }

}
