package Environment;


/**
* Environment/MonitoringStationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:02 AM British Summer Time
*/

public interface MonitoringStationOperations 
{
  String station_name ();
  String group_name ();
  String location ();
  float alarming_level ();
  void alarming_level (float newAlarming_level);
  Environment.Reading get_reading ();
  void turn_on ();
  void turn_off ();
  void reset ();
} // interface MonitoringStationOperations
