package Environment;


/**
* Environment/MonitoringStation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:02 AM British Summer Time
*/

public interface MonitoringStation extends MonitoringStationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MonitoringStation
