package Environment;


/**
* Environment/MonitoringStationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:02 AM British Summer Time
*/

public abstract class MonitoringStationPOA extends org.omg.PortableServer.Servant
 implements Environment.MonitoringStationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_station_name", new java.lang.Integer (0));
    _methods.put ("_get_group_name", new java.lang.Integer (1));
    _methods.put ("_get_location", new java.lang.Integer (2));
    _methods.put ("_get_alarming_level", new java.lang.Integer (3));
    _methods.put ("_set_alarming_level", new java.lang.Integer (4));
    _methods.put ("get_reading", new java.lang.Integer (5));
    _methods.put ("turn_on", new java.lang.Integer (6));
    _methods.put ("turn_off", new java.lang.Integer (7));
    _methods.put ("reset", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Environment/MonitoringStation/_get_station_name
       {
         String $result = null;
         $result = this.station_name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Environment/MonitoringStation/_get_group_name
       {
         String $result = null;
         $result = this.group_name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // Environment/MonitoringStation/_get_location
       {
         String $result = null;
         $result = this.location ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Environment/MonitoringStation/_get_alarming_level
       {
         float $result = (float)0;
         $result = this.alarming_level ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 4:  // Environment/MonitoringStation/_set_alarming_level
       {
         float newAlarming_level = in.read_float ();
         this.alarming_level (newAlarming_level);
         out = $rh.createReply();
         break;
       }

       case 5:  // Environment/MonitoringStation/get_reading
       {
         Environment.Reading $result = null;
         $result = this.get_reading ();
         out = $rh.createReply();
         Environment.ReadingHelper.write (out, $result);
         break;
       }

       case 6:  // Environment/MonitoringStation/turn_on
       {
         this.turn_on ();
         out = $rh.createReply();
         break;
       }

       case 7:  // Environment/MonitoringStation/turn_off
       {
         this.turn_off ();
         out = $rh.createReply();
         break;
       }

       case 8:  // Environment/MonitoringStation/reset
       {
         this.reset ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Environment/MonitoringStation:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MonitoringStation _this() 
  {
    return MonitoringStationHelper.narrow(
    super._this_object());
  }

  public MonitoringStation _this(org.omg.CORBA.ORB orb) 
  {
    return MonitoringStationHelper.narrow(
    super._this_object(orb));
  }


} // class MonitoringStationPOA
