package Environment;

/**
* Environment/MonitoringStationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:02 AM British Summer Time
*/

public final class MonitoringStationHolder implements org.omg.CORBA.portable.Streamable
{
  public Environment.MonitoringStation value = null;

  public MonitoringStationHolder ()
  {
  }

  public MonitoringStationHolder (Environment.MonitoringStation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Environment.MonitoringStationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Environment.MonitoringStationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Environment.MonitoringStationHelper.type ();
  }

}
