package Environment;

/**
* Environment/ReadingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:02 AM British Summer Time
*/

public final class ReadingHolder implements org.omg.CORBA.portable.Streamable
{
  public Environment.Reading value = null;

  public ReadingHolder ()
  {
  }

  public ReadingHolder (Environment.Reading initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Environment.ReadingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Environment.ReadingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Environment.ReadingHelper.type ();
  }

}
