package Environment;


/**
* Environment/RegionalCentreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:03 AM British Summer Time
*/

public interface RegionalCentreOperations 
{
  String name ();
  Environment.Reading[] log ();
  void raise_alarm (Environment.Reading alarmReading);
  Environment.Reading[] take_readings ();
  void add_monitoring_station (String station_name, String station_group, String station_location);
} // interface RegionalCentreOperations
