package Environment;


/**
* Environment/RegionalCentrePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:03 AM British Summer Time
*/

public abstract class RegionalCentrePOA extends org.omg.PortableServer.Servant
 implements Environment.RegionalCentreOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_name", new java.lang.Integer (0));
    _methods.put ("_get_log", new java.lang.Integer (1));
    _methods.put ("raise_alarm", new java.lang.Integer (2));
    _methods.put ("take_readings", new java.lang.Integer (3));
    _methods.put ("add_monitoring_station", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Environment/RegionalCentre/_get_name
       {
         String $result = null;
         $result = this.name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Environment/RegionalCentre/_get_log
       {
         Environment.Reading $result[] = null;
         $result = this.log ();
         out = $rh.createReply();
         Environment.Log_of_alarm_readingsHelper.write (out, $result);
         break;
       }

       case 2:  // Environment/RegionalCentre/raise_alarm
       {
         Environment.Reading alarmReading = Environment.ReadingHelper.read (in);
         this.raise_alarm (alarmReading);
         out = $rh.createReply();
         break;
       }

       case 3:  // Environment/RegionalCentre/take_readings
       {
         Environment.Reading $result[] = null;
         $result = this.take_readings ();
         out = $rh.createReply();
         Environment.Set_of_readingsHelper.write (out, $result);
         break;
       }

       case 4:  // Environment/RegionalCentre/add_monitoring_station
       {
         String station_name = in.read_string ();
         String station_group = in.read_string ();
         String station_location = in.read_string ();
         this.add_monitoring_station (station_name, station_group, station_location);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Environment/RegionalCentre:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RegionalCentre _this() 
  {
    return RegionalCentreHelper.narrow(
    super._this_object());
  }

  public RegionalCentre _this(org.omg.CORBA.ORB orb) 
  {
    return RegionalCentreHelper.narrow(
    super._this_object(orb));
  }


} // class RegionalCentrePOA
