package Environment;


/**
* Environment/Set_of_readingsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:02 AM British Summer Time
*/

abstract public class Set_of_readingsHelper
{
  private static String  _id = "IDL:Environment/Set_of_readings:1.0";

  public static void insert (org.omg.CORBA.Any a, Environment.Reading[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Environment.Reading[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Environment.ReadingHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Environment.Set_of_readingsHelper.id (), "Set_of_readings", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Environment.Reading[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Environment.Reading value[] = null;
    int _len0 = istream.read_long ();
    value = new Environment.Reading[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Environment.ReadingHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Environment.Reading[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Environment.ReadingHelper.write (ostream, value[_i0]);
  }

}
