package Environment;


/**
* Environment/Set_of_readingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Environment.idl
* Friday, April 6, 2018 at 1:44:02 AM British Summer Time
*/

public final class Set_of_readingsHolder implements org.omg.CORBA.portable.Streamable
{
  public Environment.Reading value[] = null;

  public Set_of_readingsHolder ()
  {
  }

  public Set_of_readingsHolder (Environment.Reading[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Environment.Set_of_readingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Environment.Set_of_readingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Environment.Set_of_readingsHelper.type ();
  }

}
