# DO NOT EDIT THIS FILE!
#
# Python module Environment__POA generated by omniidl

import omniORB
omniORB.updateModule("Environment__POA")

# ** 1. Stub files contributing to this module
import Environment_idl

# ** 2. Sub-modules

# ** 3. End
